In [1]:
print("OK")

OK

###### Data Link: https://www.kaggle.com/datasets/ra4u12/bookrecommendation

In [1]:
import pandas as pd
import numpy as np

In [7]:
books = pd.read_csv('BX-Books.csv', sep=';', encoding='latin-1', on_bad_lines='skip')

C:\Users\smart\AppData\Local\Temp\ipykernel_14960\3468227529.py:1: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('BX-Books.csv', sep=';', encoding='latin-1', on_bad_lines='skip')

In [8]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [9]:
books.iloc[10]['Image-URL-L']

'http://images.amazon.com/images/P/0771074670.01.LZZZZZZZ.jpg'

In [10]:
books.shape

(271360, 8)

In [11]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='str')

In [12]:
books = books[['ISBN','Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher','Image-URL-L']]

In [13]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [14]:
# Lets remane some wierd columns name
books.rename(columns={"Book-Title":'title',
                      'Book-Author':'author',
                     "Year-Of-Publication":'year',
                     "Publisher":"publisher",
                     "Image-URL-L":"image_url"},inplace=True)

In [15]:
books.head()

,ISBN,title,author,year,publisher,image_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...


In pandas, the `inplace` parameter determines whether the operation modifies the **original**
DataFrame directly or returns a **new** DataFrame with the changes applied.

Here is the breakdown of the two behaviors:

### 1. When `inplace=False` (The Default)
If you don't include `inplace=True`, pandas creates a **copy** of your DataFrame. The original
`books` DataFrame remains unchanged, and the renamed version is sent to a new variable.

To save the changes, you would have to write it like this:
```python
# You must assign it back to the variable to keep the changes
books = books.rename(columns={"Book-Title":'title', ...})
```

### 2. When `inplace=True` (Your Code)
When you set `inplace=True`, pandas performs the operation on the **existing** `books`
DataFrame. It modifies the object in your computer's memory directly.

*   **The Original is changed:** The `books` variable now permanently has the new column names.
*   **It returns `None`:** This is a crucial detail. Because the function modifies the object
and returns nothing, you **should not** assign it back to a variable.

---

### Summary Table

| Feature | `inplace=False` (Default) | `inplace=True` |
| :--- | :--- | :--- |
| **Original DataFrame** | Stays the same | Is modified |
| **Return Value** | A new DataFrame | `None` |
| **How to use it** | `df = df.rename(...)` | `df.rename(..., inplace=True)` |

### A Pro-Tip/Warning
In modern Python/Pandas development, there is a growing trend to **avoid** using `inplace=True`.


Many expert developers prefer the `df = df.rename(...)` approach (the default) because:
1.  **It's clearer:** You can clearly see that the variable `df` is being updated.
2.  **It prevents "SettingWithCopy" warnings:** Sometimes `inplace` can behave unpredictably
when working with "slices" of dataframes.
3.  **Method Chaining:** You can chain multiple operations together (e.g.,
`df.rename(...).dropna().reset_index()`) only if you use the default `inplace=False` behavior.

In [17]:
# Now load the second dataframe

users = pd.read_csv('BX-Users.csv', sep=";", on_bad_lines='skip', encoding='latin-1')

In [18]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [19]:
users.shape

(278858, 3)

In [20]:
# Lets remane some wierd columns name
users.rename(columns={"User-ID":'user_id',
                      'Location':'location',
                     "Age":'age'},inplace=True)

In [21]:
users.head()

   user_id                            location   age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [22]:
# Now load the third dataframe

ratings = pd.read_csv('BX-Book-Ratings.csv', sep=";", on_bad_lines='skip', encoding='latin-1')

In [23]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [24]:
ratings.shape

(1149780, 3)

In [25]:
# Lets remane some wierd columns name
ratings.rename(columns={"User-ID":'user_id',
                      'Book-Rating':'rating'},inplace=True)

In [26]:
ratings.head()

   user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [27]:
print(books.shape, users.shape, ratings.shape, sep='\n')

(271360, 6)
(278858, 3)
(1149780, 3)

In [28]:
ratings['user_id'].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
276697        1
276706        1
276709        1
276721        1
276723        1
Name: count, Length: 105283, dtype: int64

In [29]:
# Lets store users who had at least rated more than 200 books
x = ratings['user_id'].value_counts() > 200

In [30]:
x

user_id
11676      True
198711     True
153662     True
98391      True
35859      True
          ...
276697    False
276706    False
276709    False
276721    False
276723    False
Name: count, Length: 105283, dtype: bool

In [31]:
x[x].shape

(899,)

In [32]:
y= x[x].index

In [33]:
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       260183,   9856,  28634,  44296,  59727,  73681, 155916, 188951, 268622,
       274808],
      dtype='int64', name='user_id', length=899)

In [34]:
ratings = ratings[ratings['user_id'].isin(y)]

In [35]:
ratings.head()

      user_id        ISBN  rating
1456   277427  002542730X      10
1457   277427  0026217457       0
1458   277427  003008685X       8
1459   277427  0030615321       0
1460   277427  0060002050       0

In [36]:
# Now join ratings with books

ratings_with_books = ratings.merge(books, on='ISBN')

In [37]:
ratings_with_books.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...

In [38]:
number_rating = ratings_with_books.groupby('title')['rating'].count().reset_index()

This line of code is performing a very common operation in data analysis: **counting how many
times each book appears in your ratings list.**

In plain English, it is calculating the **"number of ratings per book."**

Here is the step-by-step breakdown of what is happening:

### 1. `.groupby('title')`
This tells pandas to look at the `ratings_with_books` DataFrame and group all the rows that have
the same **title** together.
*   *Imagine you have a pile of 1,000 rating slips. This step is like sorting them into separate
piles, where each pile contains all the ratings for one specific book.*

### 2. `['rating']`
Now that you have your groups (piles), this tells pandas: "I only care about the data in the
**'rating'** column."
*   *You are telling pandas to ignore the author, publisher, or date, and only look at the
actual rating values within those piles.*

### 3. `.count()`
This is the math part. It counts how many entries (non-null values) exist in the 'rating' column
for each group.
*   *Since every row in your group represents one person's rating, counting the rows tells you
how many people rated that specific book.*

### 4. `.reset_index()`
This is a structural step. When you use `groupby`, pandas turns the column you grouped by
(`title`) into the **Index** (the bold labels on the far left). This makes the data look like a
"Series" rather than a "DataFrame."
*   `reset_index()` moves `title` back into a regular column and gives you a standard 0, 1, 2,
3... index. This makes the result much easier to work with for future plotting or merging.

---

### Visual Example

**Before (`ratings_with_books`):**

| title | rating |
| :--- | :--- |
| The Hobbit | 5 |
| The Hobbit | 4 |
| Harry Potter | 5 |
| The Hobbit | 5 |
| Harry Potter | 3 |

**Step 1, 2, & 3 (`groupby().count()`):**
*At this stage, the result is a "Series" where the title is the index.*

| title (index) | rating (value) |
| :--- | :--- |
| **The Hobbit** | 3 |
| **Harry Potter** | 2 |

**Step 4 (`reset_index()`):**
*The final result (`number_rating`) is a clean DataFrame.*

| | title | rating |
| :--- | :--- | :--- |
| **0** | The Hobbit | 3 |
| **1** | Harry Potter | 2 |

**In short: You are creating a new table that shows exactly how many ratings each book has
received.**

In [39]:
number_rating.head()

                                               title  rating
0   A Light in the Storm: The Civil War Diary of ...       2
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1
3   Beyond IBM: Leadership Marketing and Finance ...       1
4   Clifford Visita El Hospital (Clifford El Gran...       1

In [40]:
number_rating.rename(columns={'rating':'num_of_rating'},inplace=True)

In [41]:
number_rating.head()

                                               title  num_of_rating
0   A Light in the Storm: The Civil War Diary of ...              2
1                              Always Have Popsicles              1
2               Apple Magic (The Collector's series)              1
3   Beyond IBM: Leadership Marketing and Finance ...              1
4   Clifford Visita El Hospital (Clifford El Gran...              1

In [42]:
final_rating = ratings_with_books.merge(number_rating, on='title')

In [43]:
final_rating.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,7
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,1
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,1
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,13

In [44]:
# Lets take those books which got at least 50 rating of user

final_rating = final_rating[final_rating['num_of_rating'] >= 50]

In [45]:
final_rating.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,79

In [46]:
# lets drop the duplicates
final_rating.drop_duplicates(['user_id','title'],inplace=True)

In [47]:
final_rating.isnull().sum()

user_id          0
ISBN             0
rating           0
title            0
author           0
year             0
publisher        0
image_url        0
num_of_rating    0
dtype: int64

We can use the ratings field in pivot table to get the same interest of the user to build colloborative filtering.

In [48]:
# Lets create a pivot table
book_pivot = final_rating.pivot_table(columns='user_id', index='title', values= 'rating')

In [49]:
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
book_pivot.shape

(742, 888)

In [51]:
book_pivot.fillna(0, inplace=True)

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [52]:
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

K nearest neighbors accept CSR matrix.

In [53]:
from scipy.sparse import csr_matrix


---

### 1. The Concept: Dense vs. Sparse

Imagine you have a giant spreadsheet representing users and books.
*   **Rows:** Every user in your dataset (e.g., 100,000 users).
*   **Columns:** Every book in your dataset (e.g., 50,000 books).
*   **Cells:** The rating the user gave that book.

**The "Dense" Problem:**
In a real-world dataset, most users have only rated a tiny fraction of the total books
available. If you create a standard table (a "Dense" matrix), your computer will try to create a
cell for **every single possible combination**.

$100,000 \text{ users} \times 50,000 \text{ books} = 5,000,000,000 \text{ cells}$

Storing 5 billion numbers in your computer's RAM would likely cause your program to **crash**
(it would require many Gigabytes of memory). Most of those 5 billion cells would just be `0`
(meaning the user hasn't rated the book).

**The "Sparse" Solution (`csr_matrix`):**
A **Sparse Matrix** is a clever way of storing data where we **only save the non-zero values**.
Instead of storing 5 billion numbers, we only store the coordinates and the value of the actual
ratings that exist.

### 2. What does "CSR" stand for?
**CSR** stands for **Compressed Sparse Row**.

It is a specific format that organizes the data by **rows**. It is mathematically optimized to
make "row-based" operations extremely fast.

**Why is this useful for you?**
In recommendation systems, the most common math operation is finding "users similar to User A."
To do this, the computer looks at **User A's row** and compares it to other rows. Because
`csr_matrix` is optimized for rows, this calculation happens in milliseconds instead of hours.

---

### 3. A Simple Visualization

#### The Dense Way (Wasteful)
If we represent this small 3x3 matrix where only two people rated books:
```python
[[5, 0, 0],
 [0, 0, 3],
 [0, 0, 0]]
```
*The computer stores: 5, 0, 0, 0, 0, 3, 0, 0, 0 (9 numbers).*

#### The CSR Way (Efficient)
The `csr_matrix` only remembers:
1.  **Value:** 5 (at position 0,0)
2.  **Value:** 3 (at position 1,2)

*The computer stores: Only the 2 numbers that actually matter and their locations.*

---

### 4. Summary for your Project

When you see `from scipy.sparse import csr_matrix` in a recommendation system tutorial, it means
the programmer is doing this:

1.  **Mapping:** They are turning Book Titles and User IDs into numbers (indices).
2.  **Creating the Matrix:** They are taking the `ratings` dataframe and turning it into a
massive grid of Users $\times$ Books.
3.  **Compression:** They are using `csr_matrix` to "compress" that grid so that the millions of
"unrated" (zero) values don't crash the computer.

**In short: `csr_matrix` is a memory-saving superpower that allows you to perform math on
massive datasets that would otherwise be too big for your RAM to handle.**

In [54]:
book_sparse = csr_matrix(book_pivot)

In [55]:
book_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14961 stored elements and shape (742, 888)>

In [56]:
type(book_sparse)

scipy.sparse._csr.csr_matrix

In [57]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm= 'brute')

*   `algorithm` parameter in `sklearn.neighbors.NearestNeighbors`.
    *   Main options: `'brute'`, `'kd_tree'`, `'ball_tree'`, and `'auto'`.

    *   **Option 1: `'brute'` (The one the user has)**
        *   *How it works:* It calculates the distance between every single point in the
dataset. No shortcutting.
        *   *Pros:* Simple, works with any distance metric (Cosine, Euclidean, etc.).
        *   *Cons:* Extremely slow as the dataset grows (Complexity: $O(N \cdot D)$).
        *   *Best for:* Small datasets or when using complex distance metrics like 'cosine'.

    *   **Option 2: `'kd_tree'` (K-Dimensional Tree)**
        *   *How it works:* It partitions the space into hyper-rectangles (splitting on one
dimension at a time). It's a tree structure.
        *   *Pros:* Very fast for low-dimensional data (few features).
        *   *Cons:* Performance degrades significantly as the number of dimensions (features)
increases (the "Curse of Dimensionality").
        *   *Best for:* Datasets with relatively few features (e.g., < 20).

    *   **Option 3: `'ball_tree'`**
        *   *How it works:* It partitions the space into "balls" (hyperspheres) rather than
rectangles.
        *   *Pros:* Handles high-dimensional data better than `kd_tree`.
        *   *Cons:* Still suffers from the Curse of Dimensionality, just less severely than
`kd_tree`.
        *   *Best for:* Medium-to-high dimensional data where `kd_tree` fails.

    *   **Option 4: `'auto'` (The Default)**
        *   *How it works:* Scikit-learn looks at your data and picks the best algorithm
automatically.
        *   *Logic:* If the data is small, it might pick `brute`. If it's high-dimensional, it
might pick `ball_tree`.


Here is a breakdown of each one and when you should use them:

---

### 1. `'brute'` (The "Brute Force" approach)
This is what you currently have in your code.
* **How it works:** It calculates the distance between your target point and **every single
other point** in the dataset. It makes no assumptions and takes no shortcuts.
* **Pros:** It is very simple and works with **any** distance metric (like `cosine`,
`manhattan`, or `euclidean`).
* **Cons:** It is very slow as your dataset grows. If you have 1 million users, it has to do 1
million calculations for every single search.
* **When to use:** Use this when you are using **Cosine Similarity** (which is the standard for
Recommendation Systems) or when your dataset is relatively small.

### 2. `'kd_tree'` (K-Dimensional Tree)
* **How it works:** It organizes your data into a tree structure by splitting the space into
"rectangles" (hyper-rectangles). When searching, it can skip entire "branches" of the tree that
are too far away to matter.
* **Pros:** Extremely fast for searching in **low-dimensional** data (datasets with only a few
columns/features).
* **Cons:** It suffers from the **"Curse of Dimensionality."** If you have hundreds or thousands
of columns (which is common in book recommendation datasets), the tree structure becomes
inefficient, and it becomes as slow as the brute force method. It also doesn't support all
distance metrics.
* **When to use:** Use this only if your data has very few features (e.g., searching by Age,
Weight, and Height).

### 3. `'ball_tree'` (Ball Tree)
* **How it works:** Similar to `kd_tree`, but instead of splitting space into rectangles, it
partitions data into nested "spheres" (balls).
* **Pros:** It handles **high-dimensional** data much better than `kd_tree`. It is more
efficient when you have many features.
* **Cons:** It is more mathematically complex and can be slower to "build" the tree initially
than the other methods.
* **When to use:** Use this if you have a high number of features (columns) and you are using a
distance metric like `euclidean`.

### 4. `'auto'` (The Default)
* **How it works:** This is the "smart" mode. Scikit-Learn will look at your input data and
automatically decide which of the three algorithms above will be the most efficient.
* **Pros:** You don't have to worry about the math; the library chooses the best path for you.
* **Cons:** You lose control over the specific optimization.

---

### Summary Comparison Table

| Algorithm | Strategy | Best for... | Great with many columns? |
| :--- | :--- | :--- | :--- |
| **`brute`** | Check everything | **Cosine Similarity** / Small data | Yes (but slow) |
| **`kd_tree`** | Divide into rectangles | Low-dimensional data | **No** (very slow) |
| **`ball_tree`** | Divide into spheres | High-dimensional data | Yes |
| **`auto`** | Let the computer decide | General use | Yes |

### 💡 A Critical Tip for your Project
Since you are working with a **Book Recommendation System**, you are almost certainly using
**Cosine Similarity** (via `metric='cosine'`).

**`kd_tree` and `ball_tree` do not support Cosine Similarity.** They are designed for
"Euclidean" distances (straight-line distances).

**Therefore, in 99% of Recommendation System tutorials, you will see `algorithm='brute'` because
it is the only one that reliably works with the `cosine` metric.**

In [58]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [59]:
book_pivot.iloc[237,:]

user_id
254       9.0
2276      0.0
2766      0.0
2977      0.0
3363      0.0
         ...
275970    9.0
277427    0.0
277478    0.0
277639    0.0
278418    0.0
Name: Harry Potter and the Chamber of Secrets (Book 2), Length: 888, dtype: float64

In [61]:
distance, suggestion = model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1), n_neighbors=6 )

In [62]:
distance

array([[ 0.        , 67.75691847, 68.05145112, 72.277244  , 75.81556568,
        76.30203143]])

In [63]:
suggestion

array([[237, 238, 240, 241, 184, 536]])

In [64]:
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'The Cradle Will Fall'],
      dtype='str', name='title')

In [65]:
#keeping books name
book_names = book_pivot.index

In [66]:
book_names

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Cry In The Night',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='str', name='title', length=742)

In [67]:
book_names[4]

'84 Charing Cross Road'

In [68]:
final_rating.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,79

In [69]:
np.where(book_pivot.index == '4 Blondes')[0][0]

np.int64(3)

In [70]:
# final_rating['title'].value_counts()
ids = np.where(final_rating['title'] == "Harry Potter and the Chamber of Secrets (Book 2)")[0][0]

In [71]:
final_rating.iloc[ids]['image_url']

'http://images.amazon.com/images/P/0439064872.01.LZZZZZZZ.jpg'

In [72]:
book_name = []
for book_id in suggestion:
    book_name.append(book_pivot.index[book_id])

In [73]:
book_name

[Index(['Harry Potter and the Chamber of Secrets (Book 2)',
        'Harry Potter and the Goblet of Fire (Book 4)',
        'Harry Potter and the Prisoner of Azkaban (Book 3)',
        'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
        'The Cradle Will Fall'],
       dtype='str', name='title')]

In [74]:
ids_index = []
for name in book_name[0]: 
    ids = np.where(final_rating['title'] == name)[0][0]
    ids_index.append(ids)

In [76]:
ids_index

[np.int64(44),
 np.int64(321),
 np.int64(45),
 np.int64(46),
 np.int64(786),
 np.int64(2297)]

In [77]:
for idx in ids_index:
    url = final_rating.iloc[idx]['image_url']
    print(url)

http://images.amazon.com/images/P/0439064872.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0439139597.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0439136369.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/043936213X.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0446604232.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0440115450.01.LZZZZZZZ.jpg

In [79]:
import pickle
pickle.dump(model,open('artifacts/model.pkl','wb'))
pickle.dump(book_names,open('artifacts/book_names.pkl','wb'))
pickle.dump(final_rating,open('artifacts/final_rating.pkl','wb'))
pickle.dump(book_pivot,open('artifacts/book_pivot.pkl','wb'))

In [80]:
book_names

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Cry In The Night',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='str', name='title', length=742)

# Testing model

In [81]:
def recommend_book(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distance, suggestion = model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1), n_neighbors=6 )
    
    for i in range(len(suggestion)):
            books = book_pivot.index[suggestion[i]]
            for j in books:
                if j == book_name:
                    print(f"You searched '{book_name}'\n")
                    print("The suggestion books are: \n")
                else:
                    print(j)

In [82]:
book_name = "2nd Chance"
recommend_book(book_name)

You searched '2nd Chance'

The suggestion books are:

The Next Accident
The Ghost
Exclusive
Last Man Standing
Unspeakable